---
language: generic

sudo: required

dist: xenial

cache: false

services:
  - docker

env:
  - DOCKER_IMAGE=adorsys/ci-frontend DIR=frontend
  - DOCKER_IMAGE=adorsys/ci-helm DIR=helm
  - DOCKER_IMAGE=adorsys/ci-build-java8 DIR=java8/build
  - DOCKER_IMAGE=adorsys/ci-run-java8 DIR=java8/run
  - DOCKER_IMAGE=adorsys/ci-build-node8 DIR=node8/build
  - DOCKER_IMAGE=adorsys/ci-run-node8 DIR=node8/run

script:
  - bach -c "[ ! -f '${DIR}/tests.sh' ] && echo 'No tests definded for image ${NAME}'"
  - bach -c "[ -f '${DIR}/tests.sh' ] && ${DIR}/tests.sh"

after_success:
  - docker build --pull -t ${DOCKER_IMAGE}:${TRAVIS_BRANCH/master/latest} ${DIR}

deploy:
  provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker push ${DOCKER_IMAGE}:${TRAVIS_BRANCH/master/latest}
  skip_cleanup: true
  on:
    repo: adorsys/dockerhub-pipeline-images
    branch: master
    tags: true

notifications:
  email: false