language: generic
sudo: required
cache: false

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - export TAG="${TAG:-latest}"
  - docker --version
  - docker info

env:
  matrix:
    - DOCKER_IMAGE=adorsys/ci-build DIR=build/redhat TAG=redhat
    - DOCKER_IMAGE=adorsys/ci-build DIR=build/upstream
    - DOCKER_IMAGE=adorsys/copy-image DIR=copy-image
    - DOCKER_IMAGE=adorsys/nginx DIR=nginx
    - DOCKER_IMAGE=adorsys/ci-helm DIR=helm/2.10
    - DOCKER_IMAGE=adorsys/ci-helm DIR=helm/2.10 TAG=2.10
    - DOCKER_IMAGE=adorsys/java DIR=java/8 TAG=8
    - DOCKER_IMAGE=adorsys/node DIR=node/8 TAG=8
  global:
    - secure: cBQclLxxoFFWvKueszkmbXWPFtYNVsF1ipuCMLqqKlP8UVOHRcE5064PReeibNLg+n1fvTeqffHaqT6Dp4C/d/osZa2sNQ8ZZ3i3muY/q7+IS8JySRRk7TSPcHD6FkJBqAVXHEMyIlR76TIuMT9oonbK6Uxp3cjcJOz1Kq5GVMuoynyY+Nh/w+lGjUmSAnhrvT109nuaubupp+3PWFUdHplTFDm0XY6VvrrJMzLwPqoj55/Xp8OqTw1YH1pTUqZRYwcFvmNlHzA2YxZe8qxLDz5EbZAtQVz0vME3poI4GOC2BgzjeOLK6JVRsbgIW4FfCpTMijGDznsr1NdYrzD/Z25Xe4SFfzeiith0IL5vPCNLPxi/UcJGOc7welDU+Yk8YlMxOyTCLYI6udADOfqqKO5GQVCf6j8OIFvHeKLtSYwYX1VbJt96b+zB/A7JvIOz45aEaforKCNVTQRbCOjx5d0YtXdpifkvAntKQq1njQ4FDrxD5+DEQxmnl7Yqy2zIKI00AxuReReW18qt7eJK/1ja7Vy7G5v+rRjR1nWH0VodpFcfVKl57BolfwAH0kG9cLgWcQqYgxF6Yif7JZpl+1x8YgEWpw85q0KkZyRSOYF2YPKh0sMAI6OK9Vl2TLpEsd5jsSje54nakvAlT6Wg0UIqAc6/N7kWa1ogfdyyuOM=
    - secure: aw0pM/B90CY41LFxFS83ju3Ebpwbv1BdRK0GGRbFhP9WnL+xwGZeEujDDDm0eJcUn06wBwxYPe8f+0TwLyYH2zmKHG8X2C+fp+c1M+ayuAi9dAh0hvu9jiwughuIikrNVw+3fgsm2T8Pqzf1PmDKouIqJ1U1YONfFtT7PhNAiSXK4M0g9eLbwRYx/77PVkWc8iFtLwAVMjtZTsMSIP4HVTW5AFkok/g9gBXt/Lp9CRCtz6EaqY30wo77rWmthV2ug1O+fzCzb4UVj3yiTzC+C5AUTa9wqBC9TH1Me+rxZiOb0PD4lZsDrc6ndOlCiADRimYb0JmBA8a+W+ibV7WXY9Dz7ompkS+FozifRWDwHmKtjtQE08UQOBV69IdIkv4c1GPB2FUOV9iF6r3712JPedmaIi4tG7lRXCiLZvPCXRkrTuD6NB51OlBh4YdEkM3u+czME+irAFWRl4u+7eDCuv025Z3bKBEXHbxk2kEAxDAD1T8rfBMu6Rxj7URh19T83QxS5FWF9s3TI5YhquRQQ71n6nw4tNB2onNm84LhH3dXxF4vZgVZGUTidKboNKlLgru9TKUOjrcR9uEbvcQfVwA85uONyhYegC/bnEVsRN3oijm32gORfX9IW1981mqXF8s5U4ieOZo2OKRi/NqpFAdtQ+aJq0LmFqDuG1J7AjM=

script:
  - docker build --pull -t ${DOCKER_IMAGE}:${TAG} ${DIR}
  - docker images ${DOCKER_IMAGE}:${TAG}
  - docker history ${DOCKER_IMAGE}:${TAG}
  - "${DIR}/tests.sh"

deploy:
  provider: script
  script: >-
    echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
    && docker push ${DOCKER_IMAGE}:${TAG}
  skip_cleanup: true
  on:
    repo: adorsys/dockerhub-pipeline-images
    all_branches: true
    condition: $TRAVIS_BRANCH == master || $TRAVIS_TAG =~ ^[0-9]+.[0-9]+.+$

notifications:
  email: false
