---
version: '3'
services:
  ansible:
    image: adorsys/ansible
    build:
      context: ansible
  arc42_tools:
    image: adorsys/arc42-tools
    build:
      context: arc42-tools
  awscli:
    image: adorsys/awscli
    build:
      context: awscli
  ci_build:
    image: adorsys/ci-build
    build:
      context: ci-build
  ci_clair:
    image: adorsys/ci-clair
    build:
      context: ci-clair
  ci_helm_2.10:
    image: adorsys/ci-helm:2.10
    build:
      context: ci-helm/2.10
  ci_helm_2.11:
    image: adorsys/ci-helm:2.11
    build:
      context: ci-helm/2.11
  ci_helm_2.12:
    image: adorsys/ci-helm:2.12
    build:
      context: ci-helm/2.12
  ci_helm_2.13:
    image: adorsys/ci-helm:2.13
    build:
      context: ci-helm/2.13
  nginx_alpine:
    image: adorsys/nginx:alpine
    build:
      context: nginx/alpine
  nginx_centos:
    image: adorsys/nginx:centos
    build:
      context: nginx/centos
  java_alpine_11:
    image: adorsys/java:11-alpine
    build:
      context: java/alpine/11
  java_alpine_8:
    image: adorsys/java:8-alpine
    build:
      context: java/alpine/8
  java_centos_11:
    image: adorsys/java:11-centos
    build:
      context: java/centos/11
  java_centos_8:
    image: adorsys/java:8-centos
    build:
      context: java/centos/8
  java_ubi_11:
    image: adorsys/java:11-ubi
    build:
      context: java/ubi/11
  java_ubi_8:
    image: adorsys/java:8-ubi
    build:
      context: java/ubi/8
  node_alpine_10:
    image: adorsys/node:10-alpine
    build:
      context: node/alpine/10
  node_alpine_8:
    image: adorsys/node:8-alpine
    build:
      context: node/alpine/8
  node_centos_10:
    image: adorsys/node:10-centos
    build:
      context: node/centos/10
  node_centos_8:
    image: adorsys/node:8-centos
    build:
      context: node/centos/8
